[build]
  command = "cd ../.. && yarn && yarn build"
  publish = ".next"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[plugins]]
  package = "@netlify/plugin-nextjs"
