[build]
  command = "next build && next export"
  publish = "out"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[plugins]]
  package = "@netlify/plugin-nextjs"
