import { RegistryStyles } from "@kaiju-ui/theme";
import "@kaiju-ui/theme/global.scss";
import { Montserrat } from "next/font/google";
const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.png" type="image/png" />
      </head>
      <body className={montserrat.className}>
        <RegistryStyles>{children}</RegistryStyles>
      </body>
    </html>
  );
}
